#!/usr/bin/env bash
dir=$1
shift
for file in "$@"; do
    awk -vpath="$dir" -vfile="$(basename "$file")" '/^;;.*--$/&&tag{tag=""}/^;; .* --/&&!tag{tag=$2;next}tag{print $0 > path "/" file "_" tag}' "$file"
done
